### ISSUE TITLE
Non-dates in staffing points date input field cause error

### ISSUE THREAD

**Issue by nathunsmitty** [uclaradio/uclaradio.com#149]
## Context

I tried to submit staffing points and they failed!

## Expected Behavior

We would check that a date is input client side so a user can't submit a non-date to the field. This would probably best be accomplished with an HTML date input (`<input type="date">`).

## Current Behavior

Submitting the staffing points fails.

## Possible Solution

Change the input so that it only accepts dates.

## Screenshot(s) 

![screen shot 2017-09-21 at 9 46 36 am](https://user-images.githubusercontent.com/5677971/30707941-e468b956-9eb1-11e7-8059-7896d2a84c60.png)

## Steps to Reproduce 

1. Go to uclaradio.com/staffingPoints
2. Put in a string to the date field
3. Hit submit

**Comment by binerys** [comment]
Staffing points deprecated
