### ISSUE TITLE
Staffing Points View

### ISSUE THREAD

**Issue by MatteoVH** [uclaradio/uclaradio.com#26]
Clean up the staffing points view so that users can have a prettier and more clear form.

**Comment by ChrisLaganiere** [comment]
maybe add to panel v2

**Comment by binerys** [comment]
Here are the current links to staffing points form and view: 
* https://uclaradio.com/staffingPointshttps://uclaradio.com/staffingPoints
* https://uclaradio.com/staffingPoints/view

**Comment by alexsaakyan** [comment]
![desktop hd](https://cloud.githubusercontent.com/assets/27035599/24824616/849b6a26-1bc3-11e7-9605-f3ac8e17b093.png)


Let me know what you think!

**Comment by alexsaakyan** [comment]
Can ya'll see my posts? testing 1 2 3...

**Comment by nathunsmitty** [comment]
I can! Didn't see the first one, sorry!

**Comment by binerys** [comment]
@alexsaakyan Can we move the type of activity to above the points description?

**Comment by alexsaakyan** [comment]
![desktop hd](https://cloud.githubusercontent.com/assets/27035599/26428620/99b432b4-4097-11e7-8ee9-0277cccc54d8.png)

Yo yo! Sorry I took a while I've been really busy but here it is!
