### ISSUE TITLE
Add Forgot Username and Forgot Password to new Panel mockup

### ISSUE THREAD

**Issue by haejinjo** [uclaradio/uclaradio.com#364]
also, add Rubia as a collaborator to the figmas

**Comment by m3lissacox** [comment]
I changed it to one single Forgot Username/Password screen and added checkboxes for the 2 options (as per tom's suggestion).
Mockups:
https://www.figma.com/file/ev1WvJ7fuOkv7f98wfhEHHgG/Secret-DJ-Panel
