### ISSUE TITLE
Pledge Drive 2019 Disco Theme on Frontpage

### ISSUE THREAD

**Issue by haejinjo** [uclaradio/uclaradio.com#404]
DEADLINE: APRIL 30th

This is the icing on the cake, but what would cake be without icing. Wow 'em/us.

Some things discussed:
1. An animated disco ball, somewhere conspicuous
2. Cursor trail (but with some relevant disco motif) 
3. 70's changing background onClick of cheesy bellbottom dancers (think geometric squares/circles, colorful, disco ball reflections, sequin curtains)

**Comment by arjun-raghavan-00** [comment]
Progress is on the [`arjun/pledge-drive-s19`](https://github.com/uclaradio/uclaradio.com/tree/arjun/pledge-drive-s19) branch.

**Comment by arjun-raghavan-00** [comment]
Updates include:
* Rainbow-y background (using Trianglify)
* Disco drawings (courtesy of A&D) at bottom, which are tinted random colors at page load (click on them!)
* Changed font to Comic Sans MS
* Changed banner to Pledge Drive stuff (and made it flash kind of)
* Changed logo in top left to special animated .gif
