### ISSUE TITLE
Increase number of images for a blog post

### ISSUE THREAD

**Issue by arjun-raghavan-00** [uclaradio/uclaradio.com#416]
Digi-press requested a higher number of images per post, around 10 instead of the current limit of 5.

**Comment by arjun-raghavan-00** [comment]
Instead of just adding 5 more fields, I've changed the Post schema to have a single `Cloudinary.Images` field, which allows for an arbitrary number of images in a post. It's backwards compatible, luckily, and I've updated the code in this repository to use that field if available.

**Comment by tanzeelak** [comment]
@arjun-raghavan-00 does this consistently work for you? i try to upload images and press save, but the images sometimes disappear

**Comment by arjun-raghavan-00** [comment]
Oh yeah, there's a weird bug where selecting multiple images in one go only saves the first one. It works if you select one or two images, press save, select one or two more, press save, etc etc. Weird, kind of annoying bug, but I don't know if that's a problem with Keystone or our implementation of the thing?

**Comment by arjun-raghavan-00** [comment]
[Looks like it's a Keystone issue?](https://github.com/keystonejs/keystone/issues/4857)

**Comment by arjun-raghavan-00** [comment]
Closing for now; digi-press would rather keep the current limit of 5 separate images, since making blog posts is a little frustrating for them as is. Might return to this in the future, though.
