### ISSUE TITLE
Events Panel

### ISSUE THREAD

**Issue by ChrisLaganiere** [uclaradio/uclaradio.com#57]
All managers should be able to access a new panel page which lets them enter events like ticket giveaways, info sessions.

Likely steps:
*  Create a new model to store events, something like `/database/events.js` modeled after `/database/shows.js`
* Design API routes for events panel
  * either added to `api_v1.txt` or in `api_v2.txt`
  * this can use the existing solution for authenticating users, as in `/routes/panel.js` in managers routes (see comment below)
* Design a new front-end web app ("panel v2") and set this up as the first page of the new panel with `react`, `redux`, `react-router`, `react-bootstrap` like our new frontpage
  * this should definitely be structured so that we can add on more pages later

**Comment by ChrisLaganiere** [comment]
authenticating users is pretty simple in `/routes/panel.js`, you could do this just to make sure somebody is already logged in as a manager for every action:

```
router.post('/shows/:showID', function(req, res) {
	if (req.session.user == null) {
		// not logged in, redirect to log in page
		res.redirect('/panel');
	}
	else {
		// check manager privilege
		accounts.checkPrivilege(req.session.user.username, accounts.managerPrivilegeName, function(err, hasAccess) {
			if (hasAccess) {
				// do something only managers can do
			}
			else {
				// unauthorized
				res.status(401).send(err);
			}
		});
	}
});
```

**Comment by binerys** [comment]
Moving development to https://uclaradio.com/panel/
