### ISSUE TITLE
Only allow PNG/JPG uploads and display error on Panel

### ISSUE THREAD

**Issue by binerys** [uclaradio/uclaradio.com#93]
Our  API end points for file uploading `/api/showPic` and `/api/userPic` allow any type of file to be uploaded. This has allowed hackers to upload malicious scripts onto our server 😱 

We should have the API cause non-jpg and png files to return a `403 Forbidden` response that our frontend UI on Panel will take in to display an error. 

This will require changes in the frontend and backend: 

**Backend Changes**
Check out `/routes/panel.js` to modify the API endpoints

**Frontend Changes**
Check out `/react/panelDJ.jsx` for the user pic upload frontend and `/react/panelShow.jsx` for the show art frontend

**Comment by ChrisLaganiere** [comment]
Nice, awesome investigating! We could have got around this by reformatting images when they come in, to crop to 400x400 and coincidentally filter invalid content

**Comment by binerys** [comment]
@ChrisLaganiere we found some pretty sketch stuff in our server 😨 Btw image resizing/cropping has been implemented in #89

**Comment by binerys** [comment]
Moving development to https://uclaradio.com/panel/
